server:
  port: 6060
  request:
    maxBodySize: 2048mb
    maxHeaderSize: 20mb
  
project:
  sqlPrint: false
  beanPackage: com.cym.model
  home: /home/svnWebUI/
  findPass: false
  
solon:
  app: 
    name: svnWebUI
  view:
    mapping:
      html: FreemarkerRender
  logging:
    logger:
      "io.undertow":
        level: "WARN"
      "org.xnio":
       level: "WARN"
      "o.xnio":
        level: "WARN"
      "com.zaxxer.hikari":
        level: "WARN"
      "org.jboss":
        level: "WARN"
    appender:
      file:
        name: ${project.home}/log/${solon.app.name}
        level: INFO
        maxFileSize: "100 MB"
        maxHistory: "7"
database:
  type: h2
  url: 
  username: 
  password: 
  